version: "3.8"

services:
  api:
    build: .
    ports:
      - "8085:8085"
      
    depends_on:
      - mysql
    env_file:
      - config/.env 

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Admin1q2w3e4r!
      MYSQL_DATABASE: zoo_inventory
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
